name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  chart-release:
    name: Chart Release Job
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Chart(s) to GitHub Container Registry
        run: |
          for package in .cr-release-packages/*; do
            if [ -z "${package:-}" ]; then
              break
            fi
            helm push "${package}" oci://ghcr.io/${{ github.repository_owner }}/charts
          done

      - name: Push Chart(s) to DockerHub Container Registry
        run: |
          for package in .cr-release-packages/*; do
            if [ -z "${package:-}" ]; then
              break
            fi
            helm push "${package}" oci://docker.io/hauler/charts
          done
